// Code generated by cborgen DO NOT EDIT.

package metasnapshot

import "time"

func (x ClientInfo) Msgsize() (s int) {
	s = MapHeaderSize + StringPrefixSize + len("acc") + StringPrefixSize + len(x.Account) + StringPrefixSize + len("svc") + StringPrefixSize + len(x.Service) + StringPrefixSize + len("cluster") + StringPrefixSize + len(x.Cluster)
	return
}

func (x *ClientInfo) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return AppendNil(b), nil
	}

	b = Require(b, x.Msgsize())

	count := uint32(0)
	if !(x.Account == "") {
		count++
	}
	if !(x.Service == "") {
		count++
	}
	if !(x.Cluster == "") {
		count++
	}
	b = AppendMapHeader(b, count)
	var err error
	if !(x.Account == "") {
		b = AppendString(b, "acc")
		b, err = AppendString(b, x.Account), nil
		if err != nil {
			return b, err
		}
	}
	if !(x.Service == "") {
		b = AppendString(b, "svc")
		b, err = AppendString(b, x.Service), nil
		if err != nil {
			return b, err
		}
	}
	if !(x.Cluster == "") {
		b = AppendString(b, "cluster")
		b, err = AppendString(b, x.Cluster), nil
		if err != nil {
			return b, err
		}
	}

	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *ClientInfo) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := ReadStringBytes(rest)
		if err != nil {
			return b, err
		}
		switch key {
		case "acc":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Account = tmp
		case "svc":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Service = tmp
		case "cluster":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Cluster = tmp
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *ClientInfo) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := ReadStringZC(rest)
		if err != nil {
			return b, err
		}
		key := UnsafeString(keyBytes)
		switch key {
		case "acc":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Account = UnsafeString(tmpBytes)
		case "svc":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Service = UnsafeString(tmpBytes)
		case "cluster":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Cluster = UnsafeString(tmpBytes)
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *ClientInfo) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}

func (x RaftGroup) Msgsize() (s int) {
	s = MapHeaderSize + StringPrefixSize + len("name") + StringPrefixSize + len(x.Name) + StringPrefixSize + len("peers") + ArrayHeaderSize + len(x.Peers)*StringPrefixSize + StringPrefixSize + len("cluster") + StringPrefixSize + len(x.Cluster) + StringPrefixSize + len("preferred") + StringPrefixSize + len(x.Preferred) + StringPrefixSize + len("scale_up") + BoolSize
	return
}

func (x *RaftGroup) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return AppendNil(b), nil
	}

	b = Require(b, x.Msgsize())

	count := uint32(0)
	count++
	count++
	count++
	if !(x.Cluster == "") {
		count++
	}
	if !(x.Preferred == "") {
		count++
	}
	if !(!x.ScaleUp) {
		count++
	}
	b = AppendMapHeader(b, count)
	var err error
	b = AppendString(b, "name")
	b, err = AppendString(b, x.Name), nil
	if err != nil {
		return b, err
	}

	b = AppendString(b, "peers")
	b = AppendArrayHeader(b, uint32(len(x.Peers)))
	for _, v := range x.Peers {
		b = AppendString(b, v)
	}
	b = AppendString(b, "store")
	b, err = x.Storage.MarshalCBOR(b)
	if err != nil {
		return b, err
	}
	if !(x.Cluster == "") {
		b = AppendString(b, "cluster")
		b, err = AppendString(b, x.Cluster), nil
		if err != nil {
			return b, err
		}
	}
	if !(x.Preferred == "") {
		b = AppendString(b, "preferred")
		b, err = AppendString(b, x.Preferred), nil
		if err != nil {
			return b, err
		}
	}
	if !(!x.ScaleUp) {
		b = AppendString(b, "scale_up")
		b, err = AppendBool(b, x.ScaleUp), nil
		if err != nil {
			return b, err
		}
	}

	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *RaftGroup) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := ReadStringBytes(rest)
		if err != nil {
			return b, err
		}
		switch key {
		case "name":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Name = tmp
		case "peers":

			var sz uint32
			sz, v, err = ReadArrayHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if cap(x.Peers) >= int(sz) {
				x.Peers = x.Peers[:sz]
			} else {
				x.Peers = make([]string, sz)
			}
			if sz > 0 {
				_ = x.Peers[sz-1]
			}
			for iPeers := uint32(0); iPeers < sz; iPeers++ {
				var tmp string
				tmp, v, err = ReadStringBytes(v)
				if err != nil {
					return b, err
				}
				x.Peers[iPeers] = tmp
			}
		case "store":

			v, err = x.Storage.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		case "cluster":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Cluster = tmp
		case "preferred":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Preferred = tmp
		case "scale_up":

			var tmp bool
			tmp, v, err = ReadBoolBytes(v)
			if err != nil {
				return b, err
			}
			x.ScaleUp = tmp
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *RaftGroup) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := ReadStringZC(rest)
		if err != nil {
			return b, err
		}
		key := UnsafeString(keyBytes)
		switch key {
		case "name":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Name = UnsafeString(tmpBytes)
		case "peers":

			var sz uint32
			sz, v, err = ReadArrayHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if cap(x.Peers) >= int(sz) {
				x.Peers = x.Peers[:sz]
			} else {
				x.Peers = make([]string, sz)
			}
			if sz > 0 {
				_ = x.Peers[sz-1]
			}
			for iPeers := uint32(0); iPeers < sz; iPeers++ {
				var tmp string
				tmp, v, err = ReadStringBytes(v)
				if err != nil {
					return b, err
				}
				x.Peers[iPeers] = tmp
			}
		case "store":

			v, err = x.Storage.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		case "cluster":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Cluster = UnsafeString(tmpBytes)
		case "preferred":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Preferred = UnsafeString(tmpBytes)
		case "scale_up":

			var tmp bool
			tmp, v, err = ReadBoolBytes(v)
			if err != nil {
				return b, err
			}
			x.ScaleUp = tmp
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *RaftGroup) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}

func (x SequencePair) Msgsize() (s int) {
	s = MapHeaderSize + StringPrefixSize + len("consumer_seq") + Uint64Size + StringPrefixSize + len("stream_seq") + Uint64Size
	return
}

func (x *SequencePair) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return AppendNil(b), nil
	}

	b = Require(b, x.Msgsize())

	b = AppendMapHeader(b, uint32(2))
	var err error
	b = AppendString(b, "consumer_seq")
	b, err = AppendUint64(b, x.Consumer), nil
	if err != nil {
		return b, err
	}
	b = AppendString(b, "stream_seq")
	b, err = AppendUint64(b, x.Stream), nil
	if err != nil {
		return b, err
	}

	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *SequencePair) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := ReadStringBytes(rest)
		if err != nil {
			return b, err
		}
		switch key {
		case "consumer_seq":

			var tmp uint64
			tmp, v, err = ReadUint64Bytes(v)
			if err != nil {
				return b, err
			}
			x.Consumer = tmp
		case "stream_seq":

			var tmp uint64
			tmp, v, err = ReadUint64Bytes(v)
			if err != nil {
				return b, err
			}
			x.Stream = tmp
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *SequencePair) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := ReadStringZC(rest)
		if err != nil {
			return b, err
		}
		key := UnsafeString(keyBytes)
		switch key {
		case "consumer_seq":

			var tmp uint64
			tmp, v, err = ReadUint64Bytes(v)
			if err != nil {
				return b, err
			}
			x.Consumer = tmp
		case "stream_seq":

			var tmp uint64
			tmp, v, err = ReadUint64Bytes(v)
			if err != nil {
				return b, err
			}
			x.Stream = tmp
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *SequencePair) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}

func (x Pending) Msgsize() (s int) {
	s = MapHeaderSize + StringPrefixSize + len("sequence") + Uint64Size + StringPrefixSize + len("ts") + Int64Size
	return
}

func (x *Pending) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return AppendNil(b), nil
	}

	b = Require(b, x.Msgsize())

	b = AppendMapHeader(b, uint32(2))
	var err error
	b = AppendString(b, "sequence")
	b, err = AppendUint64(b, x.Sequence), nil
	if err != nil {
		return b, err
	}
	b = AppendString(b, "ts")
	b, err = AppendInt64(b, x.Timestamp), nil
	if err != nil {
		return b, err
	}

	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *Pending) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := ReadStringBytes(rest)
		if err != nil {
			return b, err
		}
		switch key {
		case "sequence":

			var tmp uint64
			tmp, v, err = ReadUint64Bytes(v)
			if err != nil {
				return b, err
			}
			x.Sequence = tmp
		case "ts":

			var tmp int64
			tmp, v, err = ReadInt64Bytes(v)
			if err != nil {
				return b, err
			}
			x.Timestamp = tmp
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *Pending) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := ReadStringZC(rest)
		if err != nil {
			return b, err
		}
		key := UnsafeString(keyBytes)
		switch key {
		case "sequence":

			var tmp uint64
			tmp, v, err = ReadUint64Bytes(v)
			if err != nil {
				return b, err
			}
			x.Sequence = tmp
		case "ts":

			var tmp int64
			tmp, v, err = ReadInt64Bytes(v)
			if err != nil {
				return b, err
			}
			x.Timestamp = tmp
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *Pending) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}

func (x *ConsumerState) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return AppendNil(b), nil
	}

	count := uint32(0)
	count++
	count++
	if !(len(x.Pending) == 0) {
		count++
	}
	if !(len(x.Redelivered) == 0) {
		count++
	}
	b = AppendMapHeader(b, count)
	var err error
	b = AppendString(b, "delivered")
	b, err = x.Delivered.MarshalCBOR(b)
	if err != nil {
		return b, err
	}
	b = AppendString(b, "ack_floor")
	b, err = x.AckFloor.MarshalCBOR(b)
	if err != nil {
		return b, err
	}
	if !(len(x.Pending) == 0) {

		b = AppendString(b, "pending")
		b = AppendMapHeader(b, uint32(len(x.Pending)))
		for k, v := range x.Pending {
			b = AppendUint64(b, k)
			if v == nil {
				b = AppendNil(b)
			} else {
				b, err = v.MarshalCBOR(b)
				if err != nil {
					return b, err
				}
			}
		}
	}
	if !(len(x.Redelivered) == 0) {

		b = AppendString(b, "redelivered")
		b = AppendMapHeader(b, uint32(len(x.Redelivered)))
		for k, v := range x.Redelivered {
			b = AppendUint64(b, k)
			b = AppendUint64(b, v)
		}
	}

	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *ConsumerState) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := ReadStringBytes(rest)
		if err != nil {
			return b, err
		}
		switch key {
		case "delivered":

			v, err = x.Delivered.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		case "ack_floor":

			v, err = x.AckFloor.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		case "pending":

			var sz uint32
			sz, v, err = ReadMapHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if x.Pending == nil && sz > 0 {
				x.Pending = make(map[uint64]*Pending, sz)
			} else if x.Pending != nil {
				clear(x.Pending)
			}
			for iPending := uint32(0); iPending < sz; iPending++ {
				var key uint64
				key, v, err = ReadUint64Bytes(v)
				if err != nil {
					return b, err
				}
				if len(v) == 0 {
					return b, ErrShortBytes
				}
				if v[0] == 0xf6 { // null
					var tmpBytes []byte
					tmpBytes, err = ReadNilBytes(v)
					if err != nil {
						return b, err
					}
					v = tmpBytes
					x.Pending[key] = nil
					continue
				}
				tmp := new(Pending)
				v, err = tmp.UnmarshalCBOR(v)
				if err != nil {
					return b, err
				}
				x.Pending[key] = tmp
			}
		case "redelivered":

			var sz uint32
			sz, v, err = ReadMapHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if x.Redelivered == nil && sz > 0 {
				x.Redelivered = make(map[uint64]uint64, sz)
			} else if x.Redelivered != nil {
				clear(x.Redelivered)
			}
			for iRedelivered := uint32(0); iRedelivered < sz; iRedelivered++ {
				var key uint64
				key, v, err = ReadUint64Bytes(v)
				if err != nil {
					return b, err
				}
				var val uint64
				val, v, err = ReadUint64Bytes(v)
				if err != nil {
					return b, err
				}
				x.Redelivered[key] = val
			}
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *ConsumerState) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := ReadStringZC(rest)
		if err != nil {
			return b, err
		}
		key := UnsafeString(keyBytes)
		switch key {
		case "delivered":

			v, err = (&x.Delivered).DecodeTrusted(v)
			if err != nil {
				return b, err
			}
		case "ack_floor":

			v, err = (&x.AckFloor).DecodeTrusted(v)
			if err != nil {
				return b, err
			}
		case "pending":

			var sz uint32
			sz, v, err = ReadMapHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if x.Pending == nil && sz > 0 {
				x.Pending = make(map[uint64]*Pending, sz)
			}
			for iPending := uint32(0); iPending < sz; iPending++ {
				var key uint64
				key, v, err = ReadUint64Bytes(v)
				if err != nil {
					return b, err
				}
				if len(v) == 0 {
					return b, ErrShortBytes
				}
				if v[0] == 0xf6 { // null
					var tmp []byte
					tmp, err = ReadNilBytes(v)
					if err != nil {
						return b, err
					}
					v = tmp
					x.Pending[key] = nil
					continue
				}
				val := new(Pending)
				v, err = val.DecodeTrusted(v)
				if err != nil {
					return b, err
				}
				x.Pending[key] = val
			}
		case "redelivered":

			var sz uint32
			sz, v, err = ReadMapHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if x.Redelivered == nil && sz > 0 {
				x.Redelivered = make(map[uint64]uint64, sz)
			}
			for iRedelivered := uint32(0); iRedelivered < sz; iRedelivered++ {
				var key uint64
				key, v, err = ReadUint64Bytes(v)
				if err != nil {
					return b, err
				}
				var val uint64
				val, v, err = ReadUint64Bytes(v)
				if err != nil {
					return b, err
				}
				x.Redelivered[key] = val
			}
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *ConsumerState) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}

func (x WriteableConsumerAssignment) Msgsize() (s int) {
	s = MapHeaderSize + StringPrefixSize + len("created") + TimeSize + StringPrefixSize + len("name") + StringPrefixSize + len(x.Name) + StringPrefixSize + len("stream") + StringPrefixSize + len(x.Stream)
	return
}

func (x *WriteableConsumerAssignment) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return AppendNil(b), nil
	}

	b = Require(b, x.Msgsize())

	count := uint32(0)
	if !(x.Client == nil) {
		count++
	}
	count++
	count++
	count++
	count++
	count++
	if !(x.State == nil) {
		count++
	}
	b = AppendMapHeader(b, count)
	var err error
	if !(x.Client == nil) {
		b = AppendString(b, "client")
		b, err = AppendPtrMarshaler(b, x.Client)
		if err != nil {
			return b, err
		}
	}
	b = AppendString(b, "created")
	b, err = AppendTime(b, x.Created), nil
	if err != nil {
		return b, err
	}
	b = AppendString(b, "name")
	b, err = AppendString(b, x.Name), nil
	if err != nil {
		return b, err
	}
	b = AppendString(b, "stream")
	b, err = AppendString(b, x.Stream), nil
	if err != nil {
		return b, err
	}
	b = AppendString(b, "consumer")
	b, err = AppendBytes(b, []byte(x.ConfigJSON)), nil
	if err != nil {
		return b, err
	}
	b = AppendString(b, "group")
	b, err = AppendPtrMarshaler(b, x.Group)
	if err != nil {
		return b, err
	}
	if !(x.State == nil) {
		b = AppendString(b, "state")
		b, err = AppendPtrMarshaler(b, x.State)
		if err != nil {
			return b, err
		}
	}

	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *WriteableConsumerAssignment) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := ReadStringBytes(rest)
		if err != nil {
			return b, err
		}
		switch key {
		case "client":

			if x.Client == nil {
				x.Client = new(ClientInfo)
			}
			v, err = x.Client.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		case "created":

			var tmp time.Time
			tmp, v, err = ReadTimeBytes(v)
			if err != nil {
				return b, err
			}
			x.Created = tmp
		case "name":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Name = tmp
		case "stream":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Stream = tmp
		case "consumer":

			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		case "group":

			if x.Group == nil {
				x.Group = new(RaftGroup)
			}
			v, err = x.Group.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		case "state":

			if x.State == nil {
				x.State = new(ConsumerState)
			}
			v, err = x.State.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *WriteableConsumerAssignment) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := ReadStringZC(rest)
		if err != nil {
			return b, err
		}
		key := UnsafeString(keyBytes)
		switch key {
		case "client":

			if x.Client == nil {
				x.Client = new(ClientInfo)
			}
			v, err = x.Client.DecodeTrusted(v)
			if err != nil {
				return b, err
			}
		case "created":

			var tmp time.Time
			tmp, v, err = ReadTimeBytes(v)
			if err != nil {
				return b, err
			}
			x.Created = tmp
		case "name":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Name = UnsafeString(tmpBytes)
		case "stream":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Stream = UnsafeString(tmpBytes)
		case "consumer":

			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		case "group":

			if x.Group == nil {
				x.Group = new(RaftGroup)
			}
			v, err = x.Group.DecodeTrusted(v)
			if err != nil {
				return b, err
			}
		case "state":

			if x.State == nil {
				x.State = new(ConsumerState)
			}
			v, err = x.State.DecodeTrusted(v)
			if err != nil {
				return b, err
			}
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *WriteableConsumerAssignment) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}

func (x WriteableStreamAssignment) Msgsize() (s int) {
	s = MapHeaderSize + StringPrefixSize + len("created") + TimeSize + StringPrefixSize + len("sync") + StringPrefixSize + len(x.Sync)
	return
}

func (x *WriteableStreamAssignment) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return AppendNil(b), nil
	}

	b = Require(b, x.Msgsize())

	count := uint32(0)
	if !(x.Client == nil) {
		count++
	}
	count++
	count++
	count++
	count++
	if !(len(x.Consumers) == 0) {
		count++
	}
	b = AppendMapHeader(b, count)
	var err error
	if !(x.Client == nil) {
		b = AppendString(b, "client")
		b, err = AppendPtrMarshaler(b, x.Client)
		if err != nil {
			return b, err
		}
	}
	b = AppendString(b, "created")
	b, err = AppendTime(b, x.Created), nil
	if err != nil {
		return b, err
	}
	b = AppendString(b, "stream")
	b, err = AppendBytes(b, []byte(x.ConfigJSON)), nil
	if err != nil {
		return b, err
	}
	b = AppendString(b, "group")
	b, err = AppendPtrMarshaler(b, x.Group)
	if err != nil {
		return b, err
	}
	b = AppendString(b, "sync")
	b, err = AppendString(b, x.Sync), nil
	if err != nil {
		return b, err
	}
	if !(len(x.Consumers) == 0) {

		b = AppendString(b, "consumers")
		b = AppendArrayHeader(b, uint32(len(x.Consumers)))
		for _, w := range x.Consumers {
			if w == nil {
				b = AppendNil(b)
			} else {
				b, err = w.MarshalCBOR(b)
				if err != nil {
					return b, err
				}
			}
		}
	}

	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *WriteableStreamAssignment) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := ReadStringBytes(rest)
		if err != nil {
			return b, err
		}
		switch key {
		case "client":

			if x.Client == nil {
				x.Client = new(ClientInfo)
			}
			v, err = x.Client.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		case "created":

			var tmp time.Time
			tmp, v, err = ReadTimeBytes(v)
			if err != nil {
				return b, err
			}
			x.Created = tmp
		case "stream":

			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		case "group":

			if x.Group == nil {
				x.Group = new(RaftGroup)
			}
			v, err = x.Group.UnmarshalCBOR(v)
			if err != nil {
				return b, err
			}
		case "sync":

			var tmp string
			tmp, v, err = ReadStringBytes(v)
			if err != nil {
				return b, err
			}
			x.Sync = tmp
		case "consumers":

			var sz uint32
			sz, v, err = ReadArrayHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if cap(x.Consumers) >= int(sz) {
				x.Consumers = x.Consumers[:sz]
			} else {
				x.Consumers = make([]*WriteableConsumerAssignment, sz)
			}
			if sz > 0 {
				_ = x.Consumers[sz-1]
			}
			for iConsumers := uint32(0); iConsumers < sz; iConsumers++ {
				if x.Consumers[iConsumers] == nil {
					x.Consumers[iConsumers] = new(WriteableConsumerAssignment)
				}
				v, err = x.Consumers[iConsumers].UnmarshalCBOR(v)
				if err != nil {
					return b, err
				}
			}
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *WriteableStreamAssignment) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := ReadStringZC(rest)
		if err != nil {
			return b, err
		}
		key := UnsafeString(keyBytes)
		switch key {
		case "client":

			if x.Client == nil {
				x.Client = new(ClientInfo)
			}
			v, err = x.Client.DecodeTrusted(v)
			if err != nil {
				return b, err
			}
		case "created":

			var tmp time.Time
			tmp, v, err = ReadTimeBytes(v)
			if err != nil {
				return b, err
			}
			x.Created = tmp
		case "stream":

			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		case "group":

			if x.Group == nil {
				x.Group = new(RaftGroup)
			}
			v, err = x.Group.DecodeTrusted(v)
			if err != nil {
				return b, err
			}
		case "sync":

			var tmpBytes []byte
			tmpBytes, v, err = ReadStringZC(v)
			if err != nil {
				return b, err
			}
			x.Sync = UnsafeString(tmpBytes)
		case "consumers":

			var sz uint32
			sz, v, err = ReadArrayHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if cap(x.Consumers) >= int(sz) {
				x.Consumers = x.Consumers[:sz]
			} else {
				x.Consumers = make([]*WriteableConsumerAssignment, sz)
			}
			if sz > 0 {
				_ = x.Consumers[sz-1]
			}
			for iConsumers := uint32(0); iConsumers < sz; iConsumers++ {
				if x.Consumers[iConsumers] == nil {
					x.Consumers[iConsumers] = new(WriteableConsumerAssignment)
				}
				v, err = x.Consumers[iConsumers].DecodeTrusted(v)
				if err != nil {
					return b, err
				}
			}
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *WriteableStreamAssignment) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}

func (x MetaSnapshot) Msgsize() (s int) {
	s = MapHeaderSize + StringPrefixSize + len("streams") + ArrayHeaderSize + len(x.Streams)*0
	return
}

func (x *MetaSnapshot) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return AppendNil(b), nil
	}

	b = Require(b, x.Msgsize())

	b = AppendMapHeader(b, uint32(1))
	var err error

	b = AppendString(b, "streams")
	b = AppendArrayHeader(b, uint32(len(x.Streams)))
	for i := range x.Streams {
		b, err = x.Streams[i].MarshalCBOR(b)
		if err != nil {
			return b, err
		}
	}

	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *MetaSnapshot) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := ReadStringBytes(rest)
		if err != nil {
			return b, err
		}
		switch key {
		case "streams":

			var sz uint32
			sz, v, err = ReadArrayHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if cap(x.Streams) >= int(sz) {
				x.Streams = x.Streams[:sz]
			} else {
				x.Streams = make([]WriteableStreamAssignment, sz)
			}
			if sz > 0 {
				_ = x.Streams[sz-1]
			}
			for iStreams := uint32(0); iStreams < sz; iStreams++ {
				var tmp WriteableStreamAssignment
				v, err = (&tmp).UnmarshalCBOR(v)
				if err != nil {
					return b, err
				}
				x.Streams[iStreams] = tmp
			}
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *MetaSnapshot) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, ErrNotNil
	}
	sz, rest, err := ReadMapHeaderBytes(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := ReadStringZC(rest)
		if err != nil {
			return b, err
		}
		key := UnsafeString(keyBytes)
		switch key {
		case "streams":

			var sz uint32
			sz, v, err = ReadArrayHeaderBytes(v)
			if err != nil {
				return b, err
			}
			if cap(x.Streams) >= int(sz) {
				x.Streams = x.Streams[:sz]
			} else {
				x.Streams = make([]WriteableStreamAssignment, sz)
			}
			if sz > 0 {
				_ = x.Streams[sz-1]
			}
			for iStreams := uint32(0); iStreams < sz; iStreams++ {
				var tmp WriteableStreamAssignment
				v, err = (&tmp).DecodeTrusted(v)
				if err != nil {
					return b, err
				}
				x.Streams[iStreams] = tmp
			}
		default:
			v, err = Skip(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *MetaSnapshot) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}
