listen: "localhost:4222"
server_name: spiffe-e2e

tls {
  cert_file = "../../test/configs/certs/svid/server.pem"
  key_file = "../../test/configs/certs/svid/server.key"
  ca_file = "../../test/configs/certs/svid/ca.pem"
  verify = true
  insecure = true
}

accounts {
  AUTH { users [ {user: "auth", password: "auth-secret"} ] }
  APP {}
}

authorization {
  timeout: 5s
  auth_callout {
    issuer: "ABJHLOVMPA4CI6R5KLNGOB4GSLNIY7IOUPAJC4YFNDLQVIOBYQGUWVLA"
    account: AUTH
    auth_users: [ auth ]
    spiffe {
      trust_domains: ["localhost"]
    }
  }
}
