# Connection Limits
max_connections: 65536
max_subscriptions: 10000
max_sub_tokens: 16
max_control_line: 4096
max_payload: 1048576
max_pending: 67108864
max_traced_msg_len: 1024
max_closed_clients: 10000
