# JetStream Configuration
jetstream {
    store_dir: "/data/nats/jetstream"
    max_mem: 1073741824
    max_file: 10737418240
    domain: "hub"
    sync: "1m"
    # cipher: "aes"
    # key: "myencryptionkey"
    # prev_key: "myoldencryptionkey"
    # extension_hint: "o2"
    unique_tag: "az"
    max_outstanding_catchup: 67108864
    max_buffered_size: 67108864
    max_buffered_msgs: 65536
    request_queue_limit: 500
    info_queue_limit: 500
    meta_compact: 100
    meta_compact_size: 8388608
    meta_compact_sync: false

    # JetStream limits
    limits {
        max_request_batch: 256
        max_ack_pending: 65535
        max_ha_assets: 100
        duplicate_window: "2m"
    }

    # TPM options
    # tpm {
    #     keys_file: "/path/to/tpm-keys.json"
    #     encryption_password: "tpm_encrypt_pass"
    #     srk_password: "tpm_srk_pass"
    #     pcr: 7
    # }
}
