# Logging & Debugging
debug: false
trace: false
trace_verbose: false
trace_headers: false
logtime: true
logtime_utc: true
logfile: "/var/log/nats/nats-server.log"
logfile_size_limit: 104857600
logfile_max_num: 10
syslog: false
remote_syslog: "udp://syslog.example.com:514"
