commands:
  test: go test ./conf/v2/... -count=1 -v
  test_v1: go test ./conf/... -count=1
  test_server: go test ./server/... -count=1 -timeout 600s -p 1
  vet: go vet ./conf/v2/...
  vet_server: go vet ./server/...
  build: go build ./conf/v2/...
  build_server: go build ./server/...
